import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{maxWidth:'100%',height:'100%'}}>
      <body style={{width:'100%',height:'100%'}}>
        {children}
      </body>
    </html>
  );
}
